options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_PATH: "us-central1-docker.pkg.dev/counselgpt-cse239/counselgpt-image/counselgptapi"

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_IMAGE_PATH}:${SHORT_SHA}',
        'deployment'
      ]

  # 2. Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_IMAGE_PATH}:${SHORT_SHA}'
      ]

  # 3. Set Kube credentials (UPDATED REGION)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container',
        'clusters',
        'get-credentials',
        'counselgpt-cluster',
        '--region',
        'us-central1'
      ]

  # 4. Apply manifests with image override
  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: bash
    args:
      - "-c"
      - |
        kubectl set image deployment/counselgpt-api counselgpt-api=${_IMAGE_PATH}:${SHORT_SHA} --record
        kubectl apply -f k8s/gcp/

images:
  - '${_IMAGE_PATH}:${SHORT_SHA}'
