options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_PATH: "us-central1-docker.pkg.dev/counselgpt-cse239/counselgpt-image/counselgptapi"

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_IMAGE_PATH}:${SHORT_SHA}',
        'deployment'
      ]

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_IMAGE_PATH}:${SHORT_SHA}'
      ]

  # 3. Set kube credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container',
        'clusters',
        'get-credentials',
        'counselgpt-cluster',
        '--zone',
        'us-west1-a'
      ]

  # 4. Replace placeholder + apply manifests
  - name: "gcr.io/cloud-builders/kubectl"
    entrypoint: bash
    args:
      - "-c"
      - |
        sed -i "s|REPLACE_IMAGE|${_IMAGE_PATH}:${SHORT_SHA}|g" k8s/gcp/deployment.yaml
        kubectl apply -f k8s/gcp/
        kubectl rollout status deployment/counselgpt-api

images:
  - '${_IMAGE_PATH}:${SHORT_SHA}'
